import React from "react";
import Header from "../dashboard/Header";

const Analytics: React.FC = () => {
  return (
    <div className="flex flex-col md:flex-row min-h-screen text-white">
      {/* Sidebar (Header Component) */}
      <div className="w-full sm:w-1/4 lg:w-1/5 sm:h-screen">
        <Header />
      </div>

      {/* Main Content Area */}
      <div className="flex-1 p-4 md:p-8">
        {/* Page Title */}
        <div className="mb-6">
          <h1 className="text-2xl md:text-3xl font-semibold text-teal-400">Analytics Overview</h1>
          <p className="text-gray-400 mt-2 text-sm md:text-base">
            Gain insights into your shortened URLs and QR codes.
          </p>
        </div>

        {/* Analytics Cards */}
        <div className="grid gap-4 sm:gap-6 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3">
          {/* Total Shortened URLs */}
          <div className="bg-white/10 backdrop-blur-md p-4 sm:p-6 rounded-lg shadow-lg border border-white/20">
            <h3 className="text-lg md:text-xl font-semibold mb-3 text-gray-200">
              Total Shortened URLs
            </h3>
            <p className="text-teal-400 text-2xl md:text-3xl font-bold">120</p>
            <p className="text-gray-400 mt-2 text-sm md:text-base">URLs created by you so far.</p>
          </div>

          {/* Total QR Codes Generated */}
          <div className="bg-white/10 backdrop-blur-md p-4 sm:p-6 rounded-lg shadow-lg border border-white/20">
            <h3 className="text-lg md:text-xl font-semibold mb-3 text-gray-200">
              Total QR Codes
            </h3>
            <p className="text-teal-400 text-2xl md:text-3xl font-bold">50</p>
            <p className="text-gray-400 mt-2 text-sm md:text-base">QR codes generated by you.</p>
          </div>

          {/* Top Performing URL */}
          <div className="bg-white/10 backdrop-blur-md p-4 sm:p-6 rounded-lg shadow-lg border border-white/20">
            <h3 className="text-lg md:text-xl font-semibold mb-3 text-gray-200">
              Top Performing URL
            </h3>
            <p className="text-teal-400 text-sm md:text-lg font-medium truncate">
              <a href="https://short.ly/top123" className="hover:underline">
                short.ly/top123
              </a>
            </p>
            <p className="text-gray-400 mt-2 text-sm md:text-base">
              250 clicks in the last 7 days.
            </p>
          </div>
        </div>

        {/* Detailed Analytics */}
        <div className="mt-6 bg-white/10 backdrop-blur-md p-4 sm:p-6 rounded-lg shadow-lg border border-white/20">
          <h3 className="text-lg md:text-xl font-semibold mb-3 text-gray-200">Detailed Analytics</h3>
          <p className="text-gray-400 mb-4 text-sm md:text-base">
            View detailed insights into your URLs and QR codes.
          </p>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr>
                  <th className="py-3 px-4 border-b border-gray-700 text-sm md:text-base">Short URL</th>
                  <th className="py-3 px-4 border-b border-gray-700 text-sm md:text-base">Clicks</th>
                  <th className="py-3 px-4 border-b border-gray-700 text-sm md:text-base">Created At</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="py-3 px-4 border-b border-gray-800">
                    <a
                      href="https://short.ly/example1"
                      className="text-teal-400 hover:underline text-sm md:text-base"
                    >
                      short.ly/example1
                    </a>
                  </td>
                  <td className="py-3 px-4 border-b border-gray-800 text-sm md:text-base">100</td>
                  <td className="py-3 px-4 border-b border-gray-800 text-sm md:text-base">Jan 1, 2025</td>
                </tr>
                <tr>
                  <td className="py-3 px-4 border-b border-gray-800">
                    <a
                      href="https://short.ly/example2"
                      className="text-teal-400 hover:underline text-sm md:text-base"
                    >
                      short.ly/example2
                    </a>
                  </td>
                  <td className="py-3 px-4 border-b border-gray-800 text-sm md:text-base">75</td>
                  <td className="py-3 px-4 border-b border-gray-800 text-sm md:text-base">Jan 2, 2025</td>
                </tr>
                <tr>
                  <td className="py-3 px-4 border-b border-gray-800">
                    <a
                      href="https://short.ly/example3"
                      className="text-teal-400 hover:underline text-sm md:text-base"
                    >
                      short.ly/example3
                    </a>
                  </td>
                  <td className="py-3 px-4 border-b border-gray-800 text-sm md:text-base">50</td>
                  <td className="py-3 px-4 border-b border-gray-800 text-sm md:text-base">Jan 3, 2025</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Analytics;
